config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :posts

    root to: "posts#index"
  end

  devise_for :users
  root 'pages#home'
  get 'news' => "posts#index"
  get 'news/:id', to: 'posts#show', as: 'post'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      redirect_to root_path, alert: 'Not authorized.' unless current_user && access_whitelist
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
    
    private
      def access_whitelist
        current_user.role == "admin"
      end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :load_articles
  
  def after_sign_in_path_for(resource)
     admin_root_path
  end

  private

  def load_articles
    @recent_posts = Post.order("created_at DESC").limit(3)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @body_id = "home"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).per(5)
  end
  
  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogMusicband</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600' rel='stylesheet' type='text/css'>
</head>
<body<%= " class=#{@body_id}" if @body_id %>>
 <div id="page" class="container">
  <%= render 'layouts/partials/header' %>

  <div id="content">
    <% if notice %><p class="alert alert-info"><i class="fa fa-info-circle" aria-hidden="true"></i> <%= notice %></p><% end %>
    <% if alert %><p class="alert alert-danger"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i><%= alert %></p><% end %>    
    <%= yield %>
  </div>

  <%= render 'layouts/partials/footer' %>
 </div>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer>
  <div class="footer-top">
    <div class="row">
      <div class="col-sm-4">
        <h2>About us</h2>
        <div>
          Autem humanitatis omnium officiis Roma bacarum plerique domicilium virtutum suavitate Roma autem quod ingenuos ingenuos retentabant omnium autem advenas humanitatis cum dubitatur plerique nobilium bacarum non non multiformibus autem Homerici.
        </div>
      </div>
      <div class="col-sm-4">
        <h2>Vivienne’s Omitted Line</h2>
        <%= image_tag("album-03.jpg", :alt => "Aelus Vivienne’s Omitted Line album", :class => "img-responsive") %>
      </div>
      <div class="col-sm-4">
        <h2>Recent posts</h2>
        <% if @recent_posts.size > 0 %>
          <ul class="recentposts-list list-unstyled">
              <% @recent_posts.each do |recent_post| %>
                <li>
                  <%= link_to recent_post.title, post_path(recent_post.id), class: "recentposts-title" %>
                  <div class="recentposts-date"><%= recent_post.created_at.strftime("%B %d, %Y") %></div>
                </li>
              <% end %>
          </ul>
        <% else %>
          <p>There is no news for the moment.</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="footer-bottom">
    <div class="row">
      <div class="social-links">
        <ul class="list-unstyled">
          <li><a href="http://twitter.com" target="_blank"><span class="sr-only">Twitter</span><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
          <li><a href="http://facebook.com" target="_blank"><span class="sr-only">Facebook</span><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
          <li><a href="http://instagram.com" target="_blank"><span class="sr-only">Instagram</span><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
          <li><a href="http://youtube.com" target="_blank"><span class="sr-only">Youtube</span><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
          <li><a href="http://vimeo.com" target="_blank"><span class="sr-only">Vimeo</span><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
          <li><a href="http://amazon.com" target="_blank"><span class="sr-only">Amazon</span><i class="fa fa-amazon" aria-hidden="true"></i></a></li>
          <li><a href="http://apple.com" target="_blank"><span class="sr-only">Apple</span><i class="fa fa-apple" aria-hidden="true"></i></a></li>
          <li><a href="http://soundcloud.com" target="_blank"><span class="sr-only">Soundcloud</span><i class="fa fa-soundcloud" aria-hidden="true"></i></a></li>
          <li><a href="http://spotify.com" target="_blank"><span class="sr-only">Spotify</span><i class="fa fa-spotify" aria-hidden="true"></i></a></li>
        </ul>
      </div>
      <p>Music band name</p>
      <div class="admin-links">
      <% if !user_signed_in? %>
        <p class="admin-link"><%= link_to "Admin login", new_user_session_path %></p>
      <% else %>
        <% if current_user.role == "admin" %>
          <p class="admin-link"><%= link_to "Administrate", admin_root_path %></p>
        <% end %>
        <p class="admin-link"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
      <% end %>
      </div>
    </div>
  </div>
  <a href="#header" id="top-link"><span class="sr-only">Top</span><i aria-hidden="true" class="fa fa-arrow-circle-up fa-2x"></i></a>
</footer>

app/views/layouts/partials/_header.html.erb
<header id="header">
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
          <li class="<%= 'active' if current_page?(news_path) %>"><%= link_to "News", news_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="jumbotron">
    <h1>Music band name</h1>
    <p>Best band ever</p>
  </div>
</header>

app/views/pages/home.html.erb
<section class="videos">
  <div class="section-title">
    <h2>Videos</h2>
    <a class="section-more-link" href="#">All videos</a>
  </div>
  <div class="videos-list row">
    <div class="col-sm-4">
      <a href="#">
        <%= image_tag("video-like-a-rose.jpg", :alt => "Like A Rose - Ashley Monroe", :class => "img-responsive video-image") %>
        <div class="video-title">Like A Rose - Ashley Monroe</div>
      </a>
    </div>
    <div class="col-sm-4">
      <a href="#">
        <%= image_tag("video-big-love.jpg", :alt => "Big Love - Carrie Rodriguez", :class => "img-responsive video-image") %>
        <div class="video-title">Big Love - Carrie Rodriguez</div>
      </a>
    </div>
    <div class="col-sm-4">
      <a href="#">
        <%= image_tag("video-waiting-on-june.jpg", :alt => "Waiting On June - Holly Williams", :class => "img-responsive video-image") %>
        <div class="video-title">Waiting On June - Holly Williams</div>
      </a>
    </div>
  </div>
</section>
<section class="gigs">
  <div class="section-title">
    <h2>Upcoming gigs</h2>
  </div>
  <table class="table table-responsive table-hover">
    <tr>
      <td>Sep</td>
      <td>14</td>
      <td>Nashville, TN</td>
      <td>The Bluebird Cafe</td>
    </tr>
    <tr>
      <td>Sep</td>
      <td>16</td>
      <td>Seattle, WA</td>
      <td>Tractor Tavern</td>
    </tr>
    <tr>
      <td>Sep</td>
      <td>17</td>
      <td>Alexiandria, VA</td>
      <td>The Birchmere</td>
    </tr>
    <tr>
      <td>Sep</td>
      <td>25</td>
      <td>Washington, DC</td>
      <td>The Hamilton</td>
    </tr>
    <tr>
      <td>Oct</td>
      <td>30</td>
      <td>Chipping Ongar, Essex</td>
      <td>Zinc Arts Centre</td>
    </tr>
  </table>
  <a class="section-more-link" href="#">View all gigs</a>
</section>

app/views/pages/index.html.erb
<section class="videos">
  <div class="section-title">
    <h2>Videos</h2>
    <a class="section-more-link" href="#">All videos</a>
  </div>
  <div class="videos-list row">
    <div class="col-sm-4">
      <a href="#">
        <%= image_tag("video-like-a-rose.jpg", :alt => "Like A Rose - Ashley Monroe", :class => "img-responsive video-image") %>
        <div class="video-title">Like A Rose - Ashley Monroe</div>
      </a>
    </div>
    <div class="col-sm-4">
      <a href="#">
        <%= image_tag("video-big-love.jpg", :alt => "Big Love - Carrie Rodriguez", :class => "img-responsive video-image") %>
        <div class="video-title">Big Love - Carrie Rodriguez</div>
      </a>
    </div>
    <div class="col-sm-4">
      <a href="#">
        <%= image_tag("video-waiting-on-june.jpg", :alt => "Waiting On June - Holly Williams", :class => "img-responsive video-image") %>
        <div class="video-title">Waiting On June - Holly Williams</div>
      </a>
    </div>
  </div>
</section>
<section class="gigs">
  <div class="section-title">
    <h2>Upcoming gigs</h2>
  </div>
  <table class="table table-responsive table-hover">
    <tr>
      <td>Sep</td>
      <td>14</td>
      <td>Nashville, TN</td>
      <td>The Bluebird Cafe</td>
    </tr>
    <tr>
      <td>Sep</td>
      <td>16</td>
      <td>Seattle, WA</td>
      <td>Tractor Tavern</td>
    </tr>
    <tr>
      <td>Sep</td>
      <td>17</td>
      <td>Alexiandria, VA</td>
      <td>The Birchmere</td>
    </tr>
    <tr>
      <td>Sep</td>
      <td>25</td>
      <td>Washington, DC</td>
      <td>The Hamilton</td>
    </tr>
    <tr>
      <td>Oct</td>
      <td>30</td>
      <td>Chipping Ongar, Essex</td>
      <td>Zinc Arts Centre</td>
    </tr>
  </table>
  <a class="section-more-link" href="#">View all gigs</a>
</section>

app/views/posts/index.html.erb
<h1>News</h1>
<% if @posts.size > 0 %>
  <ul class="posts-list list-unstyled">
      <% @posts.each do |post| %>
        <li class="post-item">
            <h2 class="post-title"><%= link_to post.title, post_path(post.id) %></h2>
            <p class="post-date">On <%= post.created_at.strftime("%B %d, %Y") %></p>
            <div class="post-content"><%= post.content %></div>
        </li>
      <% end %>
  </ul>
  <%= paginate @posts %> 
<% else %>
  <p>There is no news for the moment.</p>
<% end %>

app/views/posts/show.html.erb
<h1>News</h1>
<div class="post">
  <h2 class="post-title"><%= @post.title %></h2>
  <p class="post-date">On <%= @post.created_at.strftime("%B %d, %Y") %></p>
  <div class="post-content"><%= @post.content %></div>
  <p class="post-more"><%= link_to '<i class="fa fa-long-arrow-left" aria-hidden="true"></i> Back'.html_safe, news_path %></p>
</div>